### ISSUE TITLE
Fails to build with ghc-7.4.2  / base 4.5.1.0

### ISSUE THREAD

**Issue by DanielG** [ekmett/tagged#22]
This is making my ghc-mod builds fail by extension, please tighten the base dependency.

```
$ cabal install tagged
Resolving dependencies...
Configuring tagged-0.8...
Building tagged-0.8...
Failed to install tagged-0.8
Build log ( /home/travis/.cabal/logs/tagged-0.8.log ):
Configuring tagged-0.8...
Dependency base ==4.5.1.0: using base-4.5.1.0
Dependency template-haskell ==2.7.0.0: using template-haskell-2.7.0.0
Using Cabal-1.22.2.0 compiled by ghc-7.4
Using compiler: ghc-7.4.2
Using install prefix: /home/travis/.cabal
Binaries installed in: /home/travis/.cabal/bin
Libraries installed in:
/home/travis/.cabal/lib/x86_64-linux-ghc-7.4.2/tagged-0.8
Private binaries installed in: /home/travis/.cabal/libexec
Data files installed in:
/home/travis/.cabal/share/x86_64-linux-ghc-7.4.2/tagged-0.8
Documentation installed in:
/home/travis/.cabal/share/doc/x86_64-linux-ghc-7.4.2/tagged-0.8
Configuration files installed in: /home/travis/.cabal/etc
Using alex version 3.0.1 found on system at: /usr/bin/alex
Using ar found on system at: /usr/bin/ar
No c2hs found
Using cpphs version 1.19 found on system at: /home/travis/.cabal/bin/cpphs
Using gcc version 4.6 found on system at: /usr/bin/gcc
Using ghc version 7.4.2 found on system at: /usr/local/ghc/7.4.2/bin/ghc
Using ghc-pkg version 7.4.2 found on system at:
/usr/local/ghc/7.4.2/bin/ghc-pkg
No ghcjs found
No ghcjs-pkg found
No greencard found
Using haddock version 2.11.0 found on system at:
/usr/local/ghc/7.4.2/bin/haddock
Using happy version 1.19.5 found on system at: /home/travis/.cabal/bin/happy
Using haskell-suite found on system at: haskell-suite-dummy-location
Using haskell-suite-pkg found on system at: haskell-suite-pkg-dummy-location
No hmake found
Using hpc version 0.6 found on system at: /usr/local/ghc/7.4.2/bin/hpc
Using hsc2hs version 0.67 found on system at: /usr/local/ghc/7.4.2/bin/hsc2hs
Using hscolour version 1.22 found on system at:
/home/travis/.cabal/bin/HsColour
No jhc found
Using ld found on system at: /usr/bin/ld
No lhc found
No lhc-pkg found
No pkg-config found
Using strip version 2.22 found on system at: /usr/bin/strip
Using tar found on system at: /bin/tar
No uhc found
Component build order: library
creating dist/build
creating dist/build/autogen
Building tagged-0.8...
Preprocessing library tagged-0.8...
Building library...
creating dist/build
/usr/local/ghc/7.4.2/bin/ghc --make -fbuilding-cabal-package -O -outputdir dist/build -odir dist/build -hidir dist/build -stubdir dist/build -i -idist/build -isrc -iold -idist/build/autogen -Idist/build/autogen -Idist/build -optP-DLANGUAGE_DeriveDataTypeable -optP-include -optPdist/build/autogen/cabal_macros.h -package-name tagged-0.8 -hide-all-packages -package-conf dist/package.conf.inplace -package-id base-4.5.1.0-66f22db3dfcd87541c9c7e50e7095d26 -package-id template-haskell-2.7.0.0-ea0103105685f73dfd311f959f3ec5a5 -XHaskell98 Data.Tagged Data.Proxy Data.Proxy.TH Paths_tagged -Wall
[1 of 4] Compiling Paths_tagged     ( dist/build/autogen/Paths_tagged.hs, dist/build/Paths_tagged.o )
[2 of 4] Compiling Data.Proxy.TH    ( src/Data/Proxy/TH.hs, dist/build/Data/Proxy/TH.o )

src/Data/Proxy/TH.hs:62:35:
    Not in scope: data constructor `PromotedConsT'

src/Data/Proxy/TH.hs:62:50:
    Not in scope: data constructor `PromotedNilT'

src/Data/Proxy/TH.hs:74:23:
    Not in scope: data constructor `PromotedConsT'

src/Data/Proxy/TH.hs:74:40:
    Not in scope: data constructor `PromotedNilT'
cabal: Error: some packages failed to install:
tagged-0.8 failed during the building phase. The exception was:
ExitFailure 1
```

**Comment by 23Skidoo** [comment]
This also causes problems for Cabal's test suite: https://travis-ci.org/haskell/cabal/jobs/56947986

**Comment by ekmett** [comment]
This looks like I screwed up the version bound for the TH test. 

Apparently the template-haskell that ships with GHC 7.4 doesn't have the PromotedNil/PromotedCons stuff, I was expecting, and I didn't have a multi-ghc travis test suite like I thought I did, so I missed it.

**Comment by ekmett** [comment]
Fixed. I revised 0.8 to restrict the bounds accordingly and uploaded 0.8.0.1 to fix the root cause so that we can build on 7.4 again properly.

**Comment by 23Skidoo** [comment]
Great, thanks for fixing this so fast.

**Comment by ekmett** [comment]
Sorry for the release hiccup. I really thought I had tested it on 7.4.
